//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChilliSoftMeetingManagement.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingItem()
        {
            this.MeetingTypeItems = new HashSet<MeetingTypeItem>();
        }
    
        public System.Guid MeetingItemId { get; set; }
        public string MeetingItemName { get; set; }
        public System.Guid MeetingItemStatusId { get; set; }
        public string PersonAssigned { get; set; }
        public string Comment { get; set; }
    
        public virtual MeetingItemStatu MeetingItemStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingTypeItem> MeetingTypeItems { get; set; }
    }
}
