//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChilliSoftMeetingManagement.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingTypeItem
    {
        public System.Guid MeetingTypeId { get; set; }
        public System.Guid MeetingItemId { get; set; }
        public System.Guid MeetingId { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual MeetingItem MeetingItem { get; set; }
        public virtual MeetingType MeetingType { get; set; }
    }
}
