//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChilliSoftMeetingManagement.Repository.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingItemStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeetingItemStatu()
        {
            this.MeetingItems = new HashSet<MeetingItem>();
        }
    
        public System.Guid MeetingItemStatusId { get; set; }
        public string MeetingItemStatusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingItem> MeetingItems { get; set; }
    }
}
